title: Welcome
email: hyeoksu.han@gmail.com
author: hshan
description: >- # this means to ignore newlines until "baseurl:"
  I'm a developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hyeoksuhan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Asia/Seoul
date_format: "%Y-%m-%d"

paginate: 5
paginate_path: "/page:num/"

show_excerpts: true
excerpt_separator: <!--more-->

theme: minima

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ""
      type: tags
    values:
      layout: tag

twitter_username: hyeoksuhan
github_username: hyeoksuhan

github: [metadata]
