title: 개발이야기
email: hyeoksu.han@gmail.com
author: hshan
description: >- # this means to ignore newlines until "baseurl:"
  지금은 서버개발자. 개발을 하면서 겪고 생각한 것들을 정리(하려고 노력하는)중.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hyeoksuhan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Asia/Seoul
date_format: "%Y-%m-%d"

paginate: 5
paginate_path: "/page:num/"

show_excerpts: true
excerpt_separator: <!--more-->

theme: minima

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ""
      type: tags
    values:
      layout: tag

stackoverflow_userid: 7129790
stackoverflow_username: hshan
github_username: hyeoksuhan

github: [metadata]

google_analytics: UA-153977054-1
